---
title: "Error quantification"
output: html_notebook
---
Depending on the available input data, we evaluated the spectre algorithm using different measures. 

## Discrepancy between target and solution
Given a known target $T$, derived for example from an empirical data set, we quantified the discrepancy $D$ between a target $T$ and a solution $S$ as:
$$D = {(\lvert T - S \rvert )  \over {\sum_{n=1}^{1000}(\lvert T - S_{rand} \rvert) / 1000}) }, $$

where $S_{rand}$ is derived from a landscape constrained to match the species richness of all sites, but species are assigned randomly to each site. Since the absolute value of $(\lvert T - S \rvert )$ is determined not only by the correctness of the solution, but depends also on landscape size and species composition (see Appendix), standardizing by the average absolute discrepancy of 1000 solutions makes $D$ a convenient measure to quantify and compare errors across landscapes of different size and species compositions. For a perfect solution, discrepancy $D$ is 0, and for a randomly assigned solution, given the constraints explained above, $D$ is approximately 1. We evaluated the performance of the spectre algorithm as the discrepancy $D_{com}$ between the commonness matrices of the target $T_{com}$ and the solution $S_{com}$. 

## Proportion of correctly predicted site x site commonness
Currently used as a second measure for error quantification by us. This measure is NOT identical to the "proportion of occurrences correctly predicted", as used by Makony et al. (2011), sorry. I misunderstood Makony's measure in the beginning. Our measure (proportion of correctly predicted site x site commonness) might be correllated to $D$, but anyway I would suggest to keep it for a while. Maybe we drop it later if we know if it adds valuable extra information or not. The proportion of correctly predicted site x site commonness $P_{correct}$is obtained from the difference between $T_{com}$ and $S_{com}$ as follows: 

$$P_{correct} = { C_{correct} \over{m}  }$$,
where $C_{correct}$ is the number of cases/sites where $T_{com}$ - $S_{com}$ == 0, and m is the number of site x site pairs for a given landscape.  



defined as: the number of all site x site pairs with a commonness difference 

## Proportion of occurrences correctly predicted 
This measure is on the level of species lists, and thus requires species labelling. Without either a kind of weighing of species occurrence probabilities at initialization, or without inclusion of species lists from a few sites as "known data", probabilities to obtain meaningful scores are low. This measure was taken from Makony et al. (2011), and has to be implemented yet. The proportion of occurrences correctly predicted $O_{correct}$ is the per site proportion of the correctly predicted species $S_{correct}$ divided by per site richness $R$, averaged across all sites:

$$ O_{correct} = \sum_{site = 1}^{site = n} { {S_{correct}} \over { {R \cdot n}} }$$.  

Please change, update, comment as you like! 