# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimizer_min_conf <- function(alpha_list, total_gamma, target, fixed_species, partial_solution, max_iterations, seed = 0L, verbose = TRUE, interruptible = TRUE) {
    .Call(`_spectre_optimizer_min_conf`, alpha_list, total_gamma, target, fixed_species, partial_solution, max_iterations, seed, verbose, interruptible)
}

calculate_solution_commonness_rcpp <- function(solution_matrix) {
    .Call(`_spectre_calculate_solution_commonness_rcpp`, solution_matrix)
}

calc_error_random_solution <- function(n, alpha_list, total_gamma, target, seed) {
    .Call(`_spectre_calc_error_random_solution`, n, alpha_list, total_gamma, target, seed)
}

