# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_solution_commonness_rcpp <- function(solution_matrix) {
    .Call('_spectre_calculate_solution_commonness_rcpp', PACKAGE = 'spectre', solution_matrix)
}

calculate_solution_commonness_site_rcpp <- function(solution_matrix, solution_commonness, site) {
    .Call('_spectre_calculate_solution_commonness_site_rcpp', PACKAGE = 'spectre', solution_matrix, solution_commonness, site)
}

update_solution_commonness_site_rcpp <- function(solution_matrix, solution_commonness, site) {
    invisible(.Call('_spectre_update_solution_commonness_site_rcpp', PACKAGE = 'spectre', solution_matrix, solution_commonness, site))
}

mh_optimizer <- function(alpha_list, total_gamma, target, max_iterations = 1000L, seed = 0L, verbose = TRUE, base_probability_jump = 1.0) {
    .Call('_spectre_mh_optimizer', PACKAGE = 'spectre', alpha_list, total_gamma, target, max_iterations, seed, verbose, base_probability_jump)
}

mh_optimizer_neutral <- function(alpha_list, total_gamma, solution_commonness_target, max_iterations = 1000L, seed = 0L, verbose = TRUE) {
    .Call('_spectre_mh_optimizer_neutral', PACKAGE = 'spectre', alpha_list, total_gamma, solution_commonness_target, max_iterations, seed, verbose)
}

calc_energy <- function(solution_commonness, solution_commonness_target) {
    .Call('_spectre_calc_energy', PACKAGE = 'spectre', solution_commonness, solution_commonness_target)
}

species_swap_rcpp <- function(mat, species, site) {
    invisible(.Call('_spectre_species_swap_rcpp', PACKAGE = 'spectre', mat, species, site))
}

#' rcpp_sample
#'
#' @description Rcpp sample function
#'
#' @param x Vector of elements to sample from.
#' @param size Size of the sample.
#' @param replace Sample with replacement.
#'
#' @details
#' \code{Rcpp} implementation of the \code{sample} function.
#'
#' @seealso
#' \code{\link{sample}}
#'
#' @return vector
#'
#' @name rcpp_sample
#' @export
rcpp_sample <- function(x, size, replace = FALSE) {
    .Call('_spectre_rcpp_sample', PACKAGE = 'spectre', x, size, replace)
}

get_swap_rows_rcpp <- function(v, cpp_index) {
    .Call('_spectre_get_swap_rows_rcpp', PACKAGE = 'spectre', v, cpp_index)
}

get_swap_rows_rcpp_bruteforce <- function(v, cpp_index) {
    .Call('_spectre_get_swap_rows_rcpp_bruteforce', PACKAGE = 'spectre', v, cpp_index)
}

which_not_vec <- function(x, y) {
    .Call('_spectre_which_not_vec', PACKAGE = 'spectre', x, y)
}

which_not <- function(x, y) {
    .Call('_spectre_which_not', PACKAGE = 'spectre', x, y)
}

