name: C/C++ unit tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: 
      - master
      - dev

jobs:
  build:

    runs-on: ubuntu-latest
    container: rocker/tidyverse

    steps:
    - uses: actions/checkout@v2
    - name: change directory
      run: cd spectre_rcpp_dev/spectre_tests
    - name: Install qmake
      run: apt-get install -y qt5-qmake  
    - name: run qmake
      run: qmake spectre_tests.pro
    - name: make
      run: make
    - name: run unit test
      run: ./spectre_tests
