name: C/C++ unit tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches: 
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    container: rocker/tidyverse
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v2
    - name: install spectre
      run: R -e 'devtools::install()'
    - name: Install deps
      run: apt update && apt install -y qt5-qmake liblzma-dev libbz2-dev
    - name: install RInside and Rcpp
      run: R -e 'install.packages(c("RInside", "Rcpp"))'
    - name: run qmake
      run: |
        cd spectre_rcpp_dev/spectre_tests
        qmake -qt=qt5 spectre_tests.pro
    - name: make
      run: |
        cd spectre_rcpp_dev/spectre_tests
        make
    - name: run unit test
      run: | 
        cd spectre_rcpp_dev/spectre_tests
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/R/lib/
        ./spectre_tests
