name: doxygen
on:
  push:
    branches:
      - doxygen
  pull_request:
    branches: 
      - doxygen

jobs:
  doxygen:
    name: 'Doxygen Action'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mattnotmitt/doxygen-action@v1
    - uses: peaceiris/actions-gh-pages@v3
      with:
        working-directory: 'src/'
        doxyfile-path: './'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dev/doc