name: R-benchmark

on:
  push:
    branches: [ dev ]
    paths-ignore: 
      - 'Rperform_Data/**'
  pull_request:
    branches: [ dev ]
    paths-ignore: 
      - '.github/workflows/**'
      - 'Rperform_Data/**'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: r-benchmark
      uses: LooDaHu/R-benchmark@test
      with:
        username: spatialecology
        commit: 5